# Porta padrão
server.port=8080

# Banco H2 em memória (não cria arquivos no disco)
spring.datasource.url=jdbc:h2:mem:visitantesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto do Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Garante que o Hibernate cria as tabelas antes de rodar o data.sql
spring.jpa.defer-datasource-initialization=true


# Criar/atualizar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console
spring.jpa.show-sql=true

# Console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
