
-- ============================
-- Brindes fictícios (50)
-- ============================
INSERT INTO brinde (nome, descricao) VALUES ('Caneca personalizada', 'Caneca com logo do evento');
INSERT INTO brinde (nome, descricao) VALUES ('Camiseta oficial', 'Camiseta exclusiva do evento');
INSERT INTO brinde (nome, descricao) VALUES ('Mochila', 'Mochila para participantes');
INSERT INTO brinde (nome, descricao) VALUES ('Boné', 'Boné estilizado do evento');
INSERT INTO brinde (nome, descricao) VALUES ('Agenda', 'Agenda personalizada');
INSERT INTO brinde (nome, descricao) VALUES ('Chaveiro', 'Chaveiro com logo');
INSERT INTO brinde (nome, descricao) VALUES ('Garrafa térmica', 'Garrafa para água ou café');
INSERT INTO brinde (nome, descricao) VALUES ('Powerbank', 'Carregador portátil');
INSERT INTO brinde (nome, descricao) VALUES ('Mousepad', 'Mousepad exclusivo');
INSERT INTO brinde (nome, descricao) VALUES ('Caneta premium', 'Caneta metálica personalizada');
INSERT INTO brinde (nome, descricao) VALUES ('Bloco de notas', 'Bloco de anotações com logo');
INSERT INTO brinde (nome, descricao) VALUES ('Ecobag', 'Sacola ecológica personalizada');
INSERT INTO brinde (nome, descricao) VALUES ('Fone de ouvido', 'Fone de ouvido bluetooth');
INSERT INTO brinde (nome, descricao) VALUES ('Relógio digital', 'Relógio esportivo');
INSERT INTO brinde (nome, descricao) VALUES ('Copo térmico', 'Copo térmico com tampa');
INSERT INTO brinde (nome, descricao) VALUES ('Carteira', 'Carteira de couro sintético');
INSERT INTO brinde (nome, descricao) VALUES ('Porta-cartão', 'Porta-cartão personalizado');
INSERT INTO brinde (nome, descricao) VALUES ('Caderno', 'Caderno universitário com logo');
INSERT INTO brinde (nome, descricao) VALUES ('Lanterna', 'Lanterna portátil');
INSERT INTO brinde (nome, descricao) VALUES ('Caixa de som', 'Caixa de som bluetooth');
INSERT INTO brinde (nome, descricao) VALUES ('Pendrive', 'Pendrive 32GB');
INSERT INTO brinde (nome, descricao) VALUES ('Carregador de carro', 'Carregador USB veicular');
INSERT INTO brinde (nome, descricao) VALUES ('Suporte para celular', 'Suporte ajustável');
INSERT INTO brinde (nome, descricao) VALUES ('Almofada', 'Almofada personalizada');
INSERT INTO brinde (nome, descricao) VALUES ('Toalha de rosto', 'Toalha bordada');
INSERT INTO brinde (nome, descricao) VALUES ('Chocolates', 'Caixa de chocolates');
INSERT INTO brinde (nome, descricao) VALUES ('Voucher cinema', 'Ingresso para cinema');
INSERT INTO brinde (nome, descricao) VALUES ('Voucher restaurante', 'Vale refeição em restaurante parceiro');
INSERT INTO brinde (nome, descricao) VALUES ('Livro', 'Livro motivacional');
INSERT INTO brinde (nome, descricao) VALUES ('Planner', 'Planner anual');
INSERT INTO brinde (nome, descricao) VALUES ('Kit café', 'Kit com café gourmet');
INSERT INTO brinde (nome, descricao) VALUES ('Kit chá', 'Kit com chás variados');
INSERT INTO brinde (nome, descricao) VALUES ('Porta-retrato', 'Porta-retrato de mesa');
INSERT INTO brinde (nome, descricao) VALUES ('Quadro decorativo', 'Quadro com arte moderna');
INSERT INTO brinde (nome, descricao) VALUES ('Pulseira fitness', 'Pulseira de atividade física');
INSERT INTO brinde (nome, descricao) VALUES ('Óculos de sol', 'Óculos estilizado');
INSERT INTO brinde (nome, descricao) VALUES ('Cesta de frutas', 'Cesta com frutas frescas');
INSERT INTO brinde (nome, descricao) VALUES ('Kit vinho', 'Garrafa de vinho com taças');
INSERT INTO brinde (nome, descricao) VALUES ('Kit cerveja', 'Cervejas artesanais');
INSERT INTO brinde (nome, descricao) VALUES ('Kit churrasco', 'Utensílios para churrasco');
INSERT INTO brinde (nome, descricao) VALUES ('Kit escritório', 'Itens de papelaria');
INSERT INTO brinde (nome, descricao) VALUES ('Kit viagem', 'Necessaire com itens de viagem');
INSERT INTO brinde (nome, descricao) VALUES ('Kit higiene', 'Produtos de higiene pessoal');
INSERT INTO brinde (nome, descricao) VALUES ('Kit beleza', 'Produtos de beleza');
INSERT INTO brinde (nome, descricao) VALUES ('Kit spa', 'Itens para relaxamento');
INSERT INTO brinde (nome, descricao) VALUES ('Kit gourmet', 'Produtos culinários especiais');
INSERT INTO brinde (nome, descricao) VALUES ('Kit tecnologia', 'Acessórios tecnológicos');
INSERT INTO brinde (nome, descricao) VALUES ('Kit esportivo', 'Itens para prática esportiva');
INSERT INTO brinde (nome, descricao) VALUES ('Kit saúde', 'Produtos de bem-estar');
INSERT INTO brinde (nome, descricao) VALUES ('Kit surpresa', 'Brinde surpresa do evento');

-- ============================
-- Visitantes fictícios (1 a 40)
-- ============================

INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 1', '1111-1111', 'visitante1@empresa.com', 'Empresa A');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 2', '2222-2222', 'visitante2@empresa.com', 'Empresa B');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 3', '3333-3333', 'visitante3@empresa.com', 'Empresa C');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 4', '4444-4444', 'visitante4@empresa.com', 'Empresa D');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 5', '5555-5555', 'visitante5@empresa.com', 'Empresa E');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 6', '6666-6666', 'visitante6@empresa.com', 'Empresa F');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 7', '7777-7777', 'visitante7@empresa.com', 'Empresa G');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 8', '8888-8888', 'visitante8@empresa.com', 'Empresa H');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 9', '9999-9999', 'visitante9@empresa.com', 'Empresa I');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 10', '1010-1010', 'visitante10@empresa.com', 'Empresa J');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 11', '1111-1111', 'visitante11@empresa.com', 'Empresa K');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 12', '1212-1212', 'visitante12@empresa.com', 'Empresa L');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 13', '1313-1313', 'visitante13@empresa.com', 'Empresa M');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 14', '1414-1414', 'visitante14@empresa.com', 'Empresa N');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 15', '1515-1515', 'visitante15@empresa.com', 'Empresa O');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 16', '1616-1616', 'visitante16@empresa.com', 'Empresa P');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 17', '1717-1717', 'visitante17@empresa.com', 'Empresa Q');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 18', '1818-1818', 'visitante18@empresa.com', 'Empresa R');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 19', '1919-1919', 'visitante19@empresa.com', 'Empresa S');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 20', '2020-2020', 'visitante20@empresa.com', 'Empresa T');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 21', '2121-2121', 'visitante21@empresa.com', 'Empresa U');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 22', '2222-2222', 'visitante22@empresa.com', 'Empresa V');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 23', '2323-2323', 'visitante23@empresa.com', 'Empresa W');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 24', '2424-2424', 'visitante24@empresa.com', 'Empresa X');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 25', '2525-2525', 'visitante25@empresa.com', 'Empresa Y');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 26', '2626-2626', 'visitante26@empresa.com', 'Empresa Z');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 27', '2727-2727', 'visitante27@empresa.com', 'Empresa A');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 28', '2828-2828', 'visitante28@empresa.com', 'Empresa B');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 29', '2929-2929', 'visitante29@empresa.com', 'Empresa C');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 30', '3030-3030', 'visitante30@empresa.com', 'Empresa D');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 31', '3131-3131', 'visitante31@empresa.com', 'Empresa E');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 32', '3232-3232', 'visitante32@empresa.com', 'Empresa F');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 33', '3333-3333', 'visitante33@empresa.com', 'Empresa G');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 34', '3434-3434', 'visitante34@empresa.com', 'Empresa H');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 35', '3535-3535', 'visitante35@empresa.com', 'Empresa I');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 36', '3636-3636', 'visitante36@empresa.com', 'Empresa J');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 37', '3737-3737', 'visitante37@empresa.com', 'Empresa K');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 38', '3838-3838', 'visitante38@empresa.com', 'Empresa L');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 39', '3939-3939', 'visitante39@empresa.com', 'Empresa M');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 40', '4040-4040', 'visitante40@empresa.com', 'Empresa N');
-- ============================
-- Visitantes fictícios (41 a 80)
-- ============================

INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 41', '4141-4141', 'visitante41@empresa.com', 'Empresa O');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 42', '4242-4242', 'visitante42@empresa.com', 'Empresa P');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 43', '4343-4343', 'visitante43@empresa.com', 'Empresa Q');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 44', '4444-4444', 'visitante44@empresa.com', 'Empresa R');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 45', '4545-4545', 'visitante45@empresa.com', 'Empresa S');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 46', '4646-4646', 'visitante46@empresa.com', 'Empresa T');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 47', '4747-4747', 'visitante47@empresa.com', 'Empresa U');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 48', '4848-4848', 'visitante48@empresa.com', 'Empresa V');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 49', '4949-4949', 'visitante49@empresa.com', 'Empresa W');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 50', '5050-5050', 'visitante50@empresa.com', 'Empresa X');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 51', '5151-5151', 'visitante51@empresa.com', 'Empresa Y');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 52', '5252-5252', 'visitante52@empresa.com', 'Empresa Z');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 53', '5353-5353', 'visitante53@empresa.com', 'Empresa A');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 54', '5454-5454', 'visitante54@empresa.com', 'Empresa B');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 55', '5555-5555', 'visitante55@empresa.com', 'Empresa C');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 56', '5656-5656', 'visitante56@empresa.com', 'Empresa D');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 57', '5757-5757', 'visitante57@empresa.com', 'Empresa E');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 58', '5858-5858', 'visitante58@empresa.com', 'Empresa F');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 59', '5959-5959', 'visitante59@empresa.com', 'Empresa G');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 60', '6060-6060', 'visitante60@empresa.com', 'Empresa H');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 61', '6161-6161', 'visitante61@empresa.com', 'Empresa I');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 62', '6262-6262', 'visitante62@empresa.com', 'Empresa J');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 63', '6363-6363', 'visitante63@empresa.com', 'Empresa K');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 64', '6464-6464', 'visitante64@empresa.com', 'Empresa L');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 65', '6565-6565', 'visitante65@empresa.com', 'Empresa M');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 66', '6666-6666', 'visitante66@empresa.com', 'Empresa N');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 67', '6767-6767', 'visitante67@empresa.com', 'Empresa O');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 68', '6868-6868', 'visitante68@empresa.com', 'Empresa P');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 69', '6969-6969', 'visitante69@empresa.com', 'Empresa Q');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 70', '7070-7070', 'visitante70@empresa.com', 'Empresa R');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 71', '7171-7171', 'visitante71@empresa.com', 'Empresa S');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 72', '7272-7272', 'visitante72@empresa.com', 'Empresa T');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 73', '7373-7373', 'visitante73@empresa.com', 'Empresa U');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 74', '7474-7474', 'visitante74@empresa.com', 'Empresa V');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 75', '7575-7575', 'visitante75@empresa.com', 'Empresa W');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 76', '7676-7676', 'visitante76@empresa.com', 'Empresa X');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 77', '7777-7777', 'visitante77@empresa.com', 'Empresa Y');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 78', '7878-7878', 'visitante78@empresa.com', 'Empresa Z');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 79', '7979-7979', 'visitante79@empresa.com', 'Empresa A');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 80', '8080-8080', 'visitante80@empresa.com', 'Empresa B');
-- ============================
-- Visitantes fictícios (81 a 122)
-- ============================

INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 81', '8181-8181', 'visitante81@empresa.com', 'Empresa C');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 82', '8282-8282', 'visitante82@empresa.com', 'Empresa D');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 83', '8383-8383', 'visitante83@empresa.com', 'Empresa E');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 84', '8484-8484', 'visitante84@empresa.com', 'Empresa F');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 85', '8585-8585', 'visitante85@empresa.com', 'Empresa G');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 86', '8686-8686', 'visitante86@empresa.com', 'Empresa H');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 87', '8787-8787', 'visitante87@empresa.com', 'Empresa I');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 88', '8888-8888', 'visitante88@empresa.com', 'Empresa J');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 89', '8989-8989', 'visitante89@empresa.com', 'Empresa K');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 90', '9090-9090', 'visitante90@empresa.com', 'Empresa L');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 91', '9191-9191', 'visitante91@empresa.com', 'Empresa M');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 92', '9292-9292', 'visitante92@empresa.com', 'Empresa N');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 93', '9393-9393', 'visitante93@empresa.com', 'Empresa O');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 94', '9494-9494', 'visitante94@empresa.com', 'Empresa P');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 95', '9595-9595', 'visitante95@empresa.com', 'Empresa Q');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 96', '9696-9696', 'visitante96@empresa.com', 'Empresa R');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 97', '9797-9797', 'visitante97@empresa.com', 'Empresa S');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 98', '9898-9898', 'visitante98@empresa.com', 'Empresa T');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 99', '9999-9999', 'visitante99@empresa.com', 'Empresa U');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 100', '100100-100', 'visitante100@empresa.com', 'Empresa V');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 101', '101101-101', 'visitante101@empresa.com', 'Empresa W');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 102', '102102-102', 'visitante102@empresa.com', 'Empresa X');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 103', '103103-103', 'visitante103@empresa.com', 'Empresa Y');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 104', '104104-104', 'visitante104@empresa.com', 'Empresa Z');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 105', '105105-105', 'visitante105@empresa.com', 'Empresa A');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 106', '106106-106', 'visitante106@empresa.com', 'Empresa B');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 107', '107107-107', 'visitante107@empresa.com', 'Empresa C');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 108', '108108-108', 'visitante108@empresa.com', 'Empresa D');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 109', '109109-109', 'visitante109@empresa.com', 'Empresa E');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 110', '110110-110', 'visitante110@empresa.com', 'Empresa F');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 111', '111111-111', 'visitante111@empresa.com', 'Empresa G');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 112', '112112-112', 'visitante112@empresa.com', 'Empresa H');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 113', '113113-113', 'visitante113@empresa.com', 'Empresa I');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 114', '114114-114', 'visitante114@empresa.com', 'Empresa J');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 115', '115115-115', 'visitante115@empresa.com', 'Empresa K');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 116', '116116-116', 'visitante116@empresa.com', 'Empresa L');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 117', '117117-117', 'visitante117@empresa.com', 'Empresa M');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 118', '118118-118', 'visitante118@empresa.com', 'Empresa N');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 119', '119119-119', 'visitante119@empresa.com', 'Empresa O');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 120', '120120-120', 'visitante120@empresa.com', 'Empresa P');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 121', '121121-121', 'visitante121@empresa.com', 'Empresa Q');
INSERT INTO visitante (nome, telefone, email, empresa) VALUES ('Visitante 122', '122122-122', 'visitante122@empresa.com', 'Empresa R');
